sudoku_proj/sudoku/urls.py
from django.urls import path

from . import views

app_name = 'sudoku'
urlpatterns = [
    path('', views.index, name='index'),
    path('play/', views.play, name='play'),
    path('makegame/', views.make_game, name='make_game'),
    path('update_board/', views.update_board, name='update_board'),
    path('upload/', views.upload, name='upload'),
    path('uploadsuccess/', views.upload_success, name='upload_success'),
    path('get_hint/', views.get_hint, name='get_hint'),
    path('erase_obvious/', views.erase_obvious, name='erase_obvious'),
    path('puzzleload/', views.puzzleload, name='puzzleload'),
    path('customgame/', views.custom_game, name='custom_game'),
    path('loadcustom/', views.load_custom, name='load_custom')
]

sudoku_proj/sudoku_proj/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sudoku/', include('sudoku.urls')),
    path('accounts/login/', auth_views.LoginView.as_view())
]

sudoku_proj/sudoku/models.py
from django.db import models


class Puzzles(models.Model):
    puzzle_id = models.AutoField(primary_key=True)
    board = models.CharField(max_length=1863, unique=True)
    solution = models.CharField(max_length=1863)
    difficulty = models.CharField(max_length=1)
    naked_single = models.IntegerField(default=0)
    hidden_single = models.IntegerField(default=0)
    naked_pair = models.IntegerField(default=0)
    omission = models.IntegerField(default=0)
    naked_triplet = models.IntegerField(default=0)
    hidden_pair = models.IntegerField(default=0)
    naked_quad = models.IntegerField(default=0)
    hidden_triplet = models.IntegerField(default=0)
    hidden_quad = models.IntegerField(default=0)
    x_wing = models.IntegerField(default=0)
    swordfish = models.IntegerField(default=0)
    xy_wing = models.IntegerField(default=0)
    unique_rectangle = models.IntegerField(default=0)

sudoku_proj/sudoku/views.py
import copy
import json
import re
import time

from django import forms
from django.contrib.admin.views.decorators import staff_member_required
from django.db import IntegrityError
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse

from .create_game import custom_board
from .models import Puzzles
from .techniques import hidden_pair, naked_quad, hidden_triplet
from .techniques import hidden_quad, xwing, swordfish
from .techniques import naked_pair, omission, naked_triplet
from .techniques import naked_single, hidden_single
from .techniques import solvable_puzzle


def index(request):
    return render(request, 'sudoku/index.html')


def new_game(request):
    if 'board' in request.session:
        return render(request, 'sudoku/index.html', {
            'previous_board_in_mem': 'True'
        })
    else:
        return render(request, 'sudoku/index.html')


def puzzleload(request):
    request.session['puzzleID'] = sanitized_puzzleid(request.POST['puzzleID'])
    return render(request, 'sudoku/puzzleload.html', )


def make_game(request):
    try:
        difficulty = sanitized_diff(request.POST['difficulty'])
        if not difficulty:
            return render(request, 'sudoku/index.html', {
                'error_message': 'Sorry, that difficulty level is not yet available.'
            })
    except KeyError:
        return render(request, 'sudoku/index.html', {
            'error_message': 'Please select a difficulty level.'
        })
    else:
        # test code: replace new_board = and solution = with new_board, solution = for production
        # new_board = json.dumps(custom_board('63214597881??9???4?4??8??1????85????16?274??????96????481529?6?753416??9296738?4?'))
        # solution = json.dumps(custom_board('632145978817692534945387612324851796169274853578963421481529367753416289296738145'))
        new_board, solution = get_game(difficulty)
        if not new_board:
            return render(request, 'sudoku/index.html', {
                'error_message': 'Sorry, we do not seem to have any puzzles at that level.'
            })
        request.session['orig_board'] = json.loads(new_board)
        request.session['board'] = json.loads(new_board)
        request.session['solution'] = json.loads(solution)
        request.session['start_time'] = round(time.time())
        if 'end_time' in request.session:
            del request.session['end_time']
        # W = Win, I = In-Progress, L = Lost, S = Surrendered
        request.session['status'] = 'I'
        request.session['hints'] = 0
        return HttpResponseRedirect(reverse('sudoku:play'))


def sanitized_diff(diff):
    try:
        if 0 < int(diff) < 5:  # set upper bound to difficulty level not yet ready
            return str(diff)
        else:
            return False
    except ValueError:
        return False


def sanitized_puzzleid(puzzleid):
    regex = r"^[0-9]+$"
    match = re.fullmatch(regex, puzzleid)
    if match:
        return str(puzzleid)
    else:
        return False


def play(request):
    return render(request, 'sudoku/play.html')


def update_board(request):
    end_time = False

    # get JavaScript sessionStorage from POST
    updated_board = json.loads(request.POST.get('board'))
    if corrupted_board(updated_board):
        # user may have tampered with JavaScript Session Data
        return HttpResponse(status=400)

    start_time = json.loads(request.POST.get('start_time'))
    if not isinstance(start_time, int):
        return HttpResponse(status=400)

    status = request.POST.get('status')
    if status not in ['W', 'L', 'I', 'S']:
        return HttpResponse(status=400)

    try:
        hints = int(request.POST.get('hints'))
    except ValueError:
        return HttpResponse(status=400)

    if status == "W" and request.session['status'] != "W":
        # wasn't won before but it is now
        end_time = round(time.time())
        request.session['end_time'] = end_time
    elif status == "W" and request.session['status'] == "W":
        # already won, don't update end time
        end_time = request.session['end_time']

    # update Django Session
    request.session['board'] = updated_board
    request.session['start_time'] = start_time
    request.session['status'] = status
    request.session['hints'] = hints

    # update SQL3 Database: W = Win, I = In-Progress, L = Lost, S = Surrendered
    data = {
            'start_time': request.session['start_time'],
            'orig_board': request.session['orig_board'],
            'current_board': request.session['board'],
            'status': request.session['status'],
            'hints': request.session['hints']
            }
    if end_time:
        data.update({'end_time': end_time})

    # uncomment save_game when not using custom board for testing, comment when testing or save will crash
    # save_game(data)
    return HttpResponse(status=204)


def corrupted_board(user_board):
    # ensure user_board hasn't been tampered with
    try:
        if len(user_board) != 9:
            raise ValueError
        for row in user_board:
            if len(row) != 9:
                raise ValueError
            for col in row:
                if isinstance(col, list):
                    if not 0 < len(col) < 10:
                        raise ValueError
                    for candidates in col:
                        if not isinstance(candidates, int):
                            raise ValueError
                        elif not 0 < candidates < 10:
                            raise ValueError
                elif not isinstance(col, int):
                    raise ValueError
                elif not 0 < col < 10:
                    raise ValueError
    except:
        return True


def upload_success(request):
    return render(request, 'sudoku/uploadsuccess.html')


class UploadFileForm(forms.Form):
    puzzle_file = forms.FileField()


@staff_member_required
def upload(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            read_file(request.FILES['puzzle_file'])
            return HttpResponseRedirect(reverse('sudoku:upload_success'))
    else:
        form = UploadFileForm()
        return render(request, 'sudoku/upload.html', {'form': form})


def get_hint(request):
    # get JavaScript sessionStorage from POST
    request.session['hints'] = request.session['hints'] + 1
    current_board = json.loads(request.POST.get('board'))
    if corrupted_board(current_board):
        # user may have tampered with JavaScript Session Data
        return HttpResponse(status=400)

    # replace length one lists with integers
    current_board = convert_board(current_board, 'Int', False)

    # level 1
    result = naked_single(current_board, hints=True)
    if result:
        return HttpResponse(json.dumps(result))
    result = hidden_single(current_board, hints=True)
    if result:
        return HttpResponse(json.dumps(result))
    # level 2
    result = naked_pair(current_board, hints=True)
    if result:
        return HttpResponse(json.dumps(result))
    result = omission(current_board, hints=True)
    if result:
        return HttpResponse(json.dumps(result))
    result = naked_triplet(current_board, hints=True)
    if result:
        return HttpResponse(json.dumps(result))
    # level 3
    result = hidden_pair(current_board, hints=True)
    if result:
        return HttpResponse(json.dumps(result))
    result = naked_quad(current_board, hints=True)
    if result:
        return HttpResponse(json.dumps(result))
    result = hidden_triplet(current_board, hints=True)
    if result:
        return HttpResponse(json.dumps(result))
    # level 4
    result = hidden_quad(current_board, hints=True)
    if result:
        return HttpResponse(json.dumps(result))
    result = xwing(current_board, hints=True)
    if result:
        return HttpResponse(json.dumps(result))
    result = swordfish(current_board, hints=True)
    if result:
        return HttpResponse(json.dumps(result))

    return HttpResponse(json.dumps(
        'Sorry, your on your own.  You may want to Verify Solutions to see if any mistakes have been made.'))


def convert_board(old_board, direction, orig_board):
    new_board = copy.deepcopy(old_board)
    if direction == 'Int':
        # user solved cells remain as length one lists to differentiate givens from user solved cells
        # This is NOT the case when using techniques to solve puzzles, and will cause issues with hints
        # We must convert single length lists (user solved cells) to integers to find correct hint
        for row in range(9):
            for col in range(9):
                if isinstance(new_board[row][col], list) and len(new_board[row][col]) == 1:
                    new_board[row][col] = new_board[row][col][0]
    elif direction == 'List':
        # convert user solved cells back to length one lists
        for row in range(9):
            for col in range(9):
                if isinstance(new_board[row][col], int) and isinstance(orig_board[row][col], list):
                    new_board[row][col] = [new_board[row][col]]
    return new_board


def erase_obvious(request):
    """Automatically remove all candidates from a cell when that candidate has already been solved in the cell's
    row, column, or block"""
    # It takes 10 minutes of tediously removing numbers from scratchpads before the board is in a state that requires
    # any mental effort.  This function automates the easy stuff so the player can focus on the more challenging
    # techniques.
    orig_board = request.session['orig_board']
    board = convert_board(request.session['board'], 'Int', False)
    progress = True
    while progress:
        progress = naked_single(board)
    board = convert_board(board, 'List', orig_board)
    response = {
        'cleaned_board': board
    }

sudoku_proj/sudoku/templates/sudoku/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            {{ page_title|default:"Sudoku" }}
        {% endblock title %}
    </title>
    <link rel="stylesheet" type="text/css" href="{%  static 'Materialize.css' %}">
    <link rel="stylesheet" type="text/css" href="{%  static 'style.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <nav class="red darken-4" role="navigation">
        <div class="nav-wrapper">
            <a class="brand-logo right">Sudoku</a>
            <ul id="nav-mobile" class="align-left">
                <li><a href="{% url 'sudoku:index' %}">New Game</a></li>
            </ul>
        </div>
    </nav>
</head>
{% block body %}
{% endblock body %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</html>

sudoku_proj/sudoku/templates/sudoku/customgame.html
{% extends 'sudoku/base.html' %}
{% load static %}
{% block title %}Create Custom Sudoku{% endblock title %}
{% block body %}
<body>
<main>
<div class="container" id="new_game_form">
    <div class="row">
        <div class="card-panel blue-grey lighten-2">
            <h2 class="center-align">Custom Sudoku Puzzle</h2>
            {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
            {% endif %}
            <form action="{% url 'sudoku:load_custom' %}" method="post">
                {% csrf_token %}
                <div class="input-field">
                </div>
                <div class="custompuzzle">
                    <label for="custompuzzle">Puzzle:</label><br>
                    <textarea id="custompuzzle" name="puzzle" cols="9" rows="9" maxlength="81"></textarea>
                </div>
                <p><input type="submit" value="Create Game"></p>
            </form>
            {% if previous_board_in_mem %}
            <button onclick="renderPlay()">Resume Previous</button>
            {% endif %}
        </div>
    </div>
</div>
<script>
    function renderPlay() {
        window.location.href = "{% url 'sudoku:play' %}";
    }
</script>
<script>
    // Source: https://codepen.io/gapcode/pen/vEJNZN
    // Get IE or Edge browser version
    var version = detectIE();

    if (version !== false && version < 12) {
        document.getElementById("new_game_form").style.display = "none";
        document.write('<h2 style="text-align: center">Internet Explorer is not supported.<br>Please upgrade to a modern browser.</h2>')
    }

    /**
     * detect IE
     * returns version of IE or false, if browser is not Internet Explorer
     */
    function detectIE() {
        var ua = window.navigator.userAgent;

        var msie = ua.indexOf('MSIE ');
        if (msie > 0) {
            // IE 10 or older => return version number
            return parseInt(ua.substring(msie + 5, ua.indexOf('.', msie)), 10);
        }

        var trident = ua.indexOf('Trident/');
        if (trident > 0) {
            // IE 11 => return version number
            var rv = ua.indexOf('rv:');
            return parseInt(ua.substring(rv + 3, ua.indexOf('.', rv)), 10);
        }

        var edge = ua.indexOf('Edge/');
        if (edge > 0) {
            // Edge (IE 12+) => return version number
            return parseInt(ua.substring(edge + 5, ua.indexOf('.', edge)), 10);
        }

        // other browser
        return false;
    }
</script>
</main>
</body>
{% endblock body %}

sudoku_proj/sudoku/templates/sudoku/index.html
{% extends 'sudoku/base.html' %}
{% load static %}
{% block title %}Start New Sudoku Game{% endblock title %}
{% block body %}
<body>
<main>
<div class="container" id="new_game_form">
    <div class="row">
        <div class="card-panel blue-grey lighten-2">
            <h2 class="center-align">Start New Game</h2>
            {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
            {% endif %}
            <form action="{% url 'sudoku:make_game' %}" method="post">
                <div class="input-field">
                    {% csrf_token %}
                </div>
                <br/>
                Difficulty Level:<br/>
                <p>
                    <input type="radio" id="disability" name="difficulty" value="1"/>
                    <label for="disability" class="black-text">Easy</label>
                </p>

                <p>
                    <input type="radio" id="intelligent" name="difficulty" value="2"/>
                    <label for="intelligent" class="black-text">Normal</label>
                </p>

                <p>
                    <input type="radio" id="bright" name="difficulty" value="3"/>
                    <label for="bright" class="black-text">Hard</label>
                </p>

                <p>
                    <input type="radio" id="gifted" name="difficulty" value="4"/>
                    <label for="gifted" class="black-text">Expert</label>
                </p>

                <p>
                    <button>Start Game</button>
                    <button type="button" onClick="createCustom()">Create Custom</button>
                    {% if previous_board_in_mem %}
                    <button type="button" onclick="renderPlay()">Resume Previous</button>
                    {% endif %}
                </p>
            </form>
        </div>
    </div>
</div>
<script>
    function renderPlay() {
        window.location.href = "{% url 'sudoku:play' %}";
    }

    function createCustom() {
        window.location.href = "{% url 'sudoku:custom_game' %}";
    }
</script>
<script>
    // Source: https://codepen.io/gapcode/pen/vEJNZN
    // Get IE or Edge browser version
    var version = detectIE();

    if (version !== false && version < 12) {
        document.getElementById("new_game_form").style.display = "none";
        document.write('<h2 style="text-align: center">Internet Explorer is not supported.<br>Please upgrade to a modern browser.</h2>');
    }

    /**
     * detect IE
     * returns version of IE or false, if browser is not Internet Explorer
     */
    function detectIE() {
        var ua = window.navigator.userAgent;

        var msie = ua.indexOf("MSIE ");
        if (msie > 0) {
            // IE 10 or older => return version number
            return parseInt(ua.substring(msie + 5, ua.indexOf(".", msie)), 10);
        }

        var trident = ua.indexOf("Trident/");
        if (trident > 0) {
            // IE 11 => return version number
            var rv = ua.indexOf("rv:");
            return parseInt(ua.substring(rv + 3, ua.indexOf(".", rv)), 10);
        }

        var edge = ua.indexOf("Edge/");
        if (edge > 0) {
            // Edge (IE 12+) => return version number
            return parseInt(ua.substring(edge + 5, ua.indexOf(".", edge)), 10);
        }

        // other browser
        return false;
    }
</script>
</main>
</body>
{% endblock body %}

sudoku_proj/sudoku/templates/sudoku/puzzleload.html
{% extends 'sudoku/base.html' %}
{% load static %}
{% block title %}Start New Sudoku Game{% endblock title %}
{% block body %}
<body onload="fillForm()">
<main>
<div class="container" id="load_puzzle_form">
    <div class="row">
        <h2 class="center-align">Load Puzzle</h2>
        {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
        {% endif %}
        <form action="{% url 'sudoku:load_puzzle' %}" method="post">
            {% csrf_token %}
            <div class="input-field">
                <label for="puzzleID" class="black-text">Puzzle ID:</label><br>
                <input type="text" id="puzzleID" name="puzzleID"
                       readonly><br>
            </div>
            <br><input type="submit" value="Load Puzzle">
        </form>
    </div>
</div>

<script>
    function fillForm() {
        var puz = "{{ request.session.puzzleID}}";
        var inputText = document.getElementById("puzzleID");
        inputText.setAttribute('value', puz);
    }
</script>
</main>
</body>
{% endblock body %}

sudoku_proj/sudoku/templates/sudoku/sudoku.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sudoku - Let's Play!</title>
</head>
<body>
Actual game board goes here.  Referred will be newgame.html where user selects game type.
</body>
</html>

sudoku_proj/sudoku/templates/sudoku/upload.html
{% extends 'sudoku/base.html' %}
{% load static %}
{% block title %}Start New Sudoku Game{% endblock title %}
{% block body %}
<body>
<main>
    <h1>Upload Puzzles</h1>
    {% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
    {% endif %}
    <form action="{% url 'sudoku:upload' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Upload">
    </form>
</main>
</body>
{% endblock body %}

sudoku_proj/sudoku/templates/sudoku/uploadsuccess.html
{% extends 'sudoku/base.html' %}
{% load static %}
{% block title %}Successful Upload{% endblock title %}
{% block body %}
<body>
<main>
    <h1>Upload Complete<br>Please manually check the DB for detailed results.</h1>
    {% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
    {% endif %}
</main>
</body>
{% endblock body %}